language: r
r:
  - release
  - devel

sudo: false
cache: packages

warnings_are_errors: true

r_packages:
  - rdtLite

r_github_packages:
  - End-to-end-provenance/provParseR
  - End-to-end-provenance/rdt

notifications:
  slack: endtoendprovenance:DNYqXZWhV1c3eRhkjGYyjCEv


